@startuml
'https://plantuml.com/class-diagram


class InventoryManagementApplicationController implements Initializable{
'attributes
-searchSerialNumberListInput :  TextField
-nameText : TextField
-searchNameListInput : TextField
-serialNumberText : TextField
-valueText : TextField
-todoTable : TableView<Item>
-errorMessage : Label
-serialNumberColumn : TableColumn<Item, String>
-valueColumn : TableColumn<Item, String>
-nameColumn : TableColumn<Item, String>
+myList : ObservableList<Item>

'methods
+initialize(URL location, ResourceBundle resources)

+validSerialNumberEntry(String value) : boolean
+validSerialNumberEntryHelper(String value) : String
-isSerialNumberDuplicate(String text) : boolean

+validValueEntry(String value) : boolean
+validValueEntryHelper(String value) : String
-parseToDoubleCheck(String value) : String

+validNameEntry(int length) : boolean
+validNameEntryHelper(int length ) : boolean

+inventoryItemsControlCount(int size) : boolean
+inventoryItemsControlCountHelper(int size) : String

+displayErrorMessage(String message)
+addItemClicked(ActionEvent event)
+loadClicked(ActionEvent event)
+saveClicked(ActionEvent event)
+removeItemClicked(ActionEvent event)
+clearAllClicked(ActionEvent actionEvent)
+nameEditTable(TableColumn.CellEditEvent<Item, String> itemStringCellEditEvent)
+valueEditTable(TableColumn.CellEditEvent<Item, String> itemStringCellEditEvent)
+serialNumberEditTable(TableColumn.CellEditEvent<Item, String> itemStringCellEditEvent)
+searchSerialNumbersColumn(String newValue, String oldValue)
+searchNameColumn(String newValue, String oldValue)

}

class InventoryManagementApplication extends javafx.application.Application {
+static void main(String[] args)
+start(Stage stage) throws Exception
}

class FileHandler {
'methods
+{static}saveList(List<Item> listItems, File file, String extensions) throws IOException
+{static}loadList(File file, String extensions) throws  ParseException, IOException : List<Item>

+{static}saveTsvFile(List<Item> listItems, File file)
+{static}saveHtmlList(List<Item> listItems, File file) throws IOException
-{static}generateHtmlRow(Item item) : String
+{static}saveJsonList(List<Item> listItems, File file) throws IOException


+{static}loadTsvList(File file) throws FileNotFoundException, ParseException List<Item>
+{static}loadHtmlList(File file) throws IOException : List<Item>
+{static}loadJsonList(File file) : List<Item>
}

class Item {
'attributes
-{static} final SERIAL_FORMAT : Pattern
-{static} final VALUE_FORMAT : Pattern
-name : SimpleStringProperty
-value : SimpleStringProperty
-serialNumber : SimpleStringProperty

'methods
+getValue() : String
+setValue(String value) throws IllegalArgumentException
+getName() : String
+setName(String name)
+setSerialNumber(String serialNumber) throws IllegalArgumentException
+getSerialNumber() : String
}

@enduml